version: '3'
services:
  # py4web前端部屬測試(編譯結果顯示)
  web:
    build: ./
    # image: docker.io/bitnami/apache:2.4-debian-10
    environment:
      # 反向代理服務機制
      - VIRTUAL_HOST=web.py4web.176.mlc.app
      - LETSENCRYPT_HOST=web.py4web.176.mlc.app
      - LETSENCRYPT_EMAIL=m0724001@gm.nuu.edu.tw
      - VIRTUAL_PORT=8000
      - DASHBOARD_PASSWORD=cccc
    expose: 
      - 8000
    volumes: 
      - ./apps:/app:rw

  vscode-melo:
    build:
      context: vscode
      dockerfile: Dockerfile
    # image: codercom/code-server:latest
    # user: "$(id -u):$(id -g)"
    restart: always
    environment:
      # 反向代理服務機制
      - VIRTUAL_HOST=melo.py4web.176.mlc.app
      - LETSENCRYPT_HOST=melo.py4web.176.mlc.app
      - LETSENCRYPT_EMAIL=m0724001@gm.nuu.edu.tw
      - VIRTUAL_PORT=8080
      #- "DOCKER_USER=$USER"
    volumes:
      - "./vscode/melo.config.yaml:/home/coder/.config/code-server/config.yaml:rw"
      - "./apps:/home/coder/apps:rw"
